language: python
dist: Xenial
python: "3.6"

install:
  # Get Migen / LiteX / Cores
  - wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
  - python3 litex_setup.py init install

script: python setup.py test
