language: python
dist: Xenial
python: "3.6"

install:
  # Get Migen / LiteX / Cores
  - cd ~/
  - wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
  - python3 litex_setup.py init install
  # Install the version being tested
  - cd $TRAVIS_BUILD_DIR
  - python3 setup.py install

script:
  - cd $TRAVIS_BUILD_DIR
  - python setup.py test
